package ar.edu.ort.balance.balanceapp.utils;

public enum PerfilEnumResponse {
    PERFIL_INVALID_NOMBRE, PERFIL_INVALID_APELLIDO, PERFIL_INVALID_MAIL, PERFIL_OK, PERFIL_ERR,
    PASSWORD_INVALID_OLD, PASSWORD_INVALID_NEW, PASSWORD_INVALID_RENEW, PASSWORD_NOT_EQUALS, PASSWORD_OK, PASSWORD_ERR
}
